### ISSUE TITLE
Remove `= null` after `Delete()`

### ISSUE THREAD

**Issue by warpech** [Starcounter/authorization#59]
According to https://github.com/Starcounter/level1/issues/2140#issuecomment-301756296, the following line can now be removed: https://github.com/Starcounter/authorization/blob/c5bfedb62d8c91b37f83239431432a30c5512457/Authorization/Partial/PermissionSelectionPartial.json.cs#L130

**Comment by joozek78** [comment]
Actually, `_permissionToken` is a field that's used in [`AssociateMemberWithPermission`](https://github.com/Starcounter/authorization/blob/c5bfedb62d8c91b37f83239431432a30c5512457/Authorization/Partial/PermissionSelectionPartial.json.cs#L89). This assignment can't be removed, otherwise `_getOrCreateToken` would misbehave
