### ISSUE TITLE
Refactor app to don't use Starcounter. namespace

### ISSUE THREAD

**Issue by miyconst** [Starcounter/authorization#63]
This library has to be refactored to don't use `Starcounter.` namespace. Explanation:

The `Starcounter.` namespace is reserved for internal Starcounter tables and classes. From time to time there are new classes to add. Once a class added there is no guarantee that some other libraries/applications have not yet taken that name, and if the name happens to be taken, it breaks the library/application.

To fix this, it was decided to bad usage of `Starcounter.` namespace outside of Starcounter internals.

It is allowed to use `StarcounterXxx`, but not `Starcounter.Xxx`.

**Comment by joozek78** [comment]
But isn't this library an official Starcounter thing? Using `Starcounter` namespace asserts that it is. It's a bit like throwing it out of `Starcounter` github org. I don't since how it differs from starcounter internals in our level of control.

Sorry it took so long to respond. Since I probably missed this discussion, if you insist I will move it out of the namespace

**Comment by joozek78** [comment]
After talking to @miyconst we agreed to not move things out of the `Starcounter` namespace yet. If we decide to do it, this task will be reopened
