### ISSUE TITLE
Adopt to changes required by Orchestrator

### ISSUE THREAD

**Issue by warpech** [Starcounter/authorization#78]
For working in Starcounter Nova and Starcounter 2.4 after https://github.com/Starcounter/Starcounter.Orchestrator/issues/2, this library neeeds to be adopted to changes required by @alemoi in Starcounter/Starcounter.Orchestrator#2

**Comment by ghost** [comment]
The adoption finished and pushed @warpech
Only the `3.x` branch was adopted. Note that I have added the `NuGet.Config`, if its not needed, please remove it.

**Comment by ghost** [comment]
The build still fails because I guess it uses latest nightly `develop`. Locally everything builds fine for me. So, waiting over the night for a successful build. Currently failing build: https://teamcity.starcounter.org/viewLog.html?buildId=82414&buildTypeId=Apps_StarcounterAuthorization_StarcounterAuthorizationMasterDevelop24&tab=buildLog

**Comment by warpech** [comment]
@joozek78 can you pls review and release a new version?

**Comment by ghost** [comment]
Now the `3.x` build succeeds: https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_StarcounterAuthorization_StarcounterAuthorization3xDevelop24&tab=buildTypeHistoryList&branch_Apps_StarcounterAuthorization=__all_branches__

Do you need any more assistance @warpech?

**Comment by PatrykSzwer** [comment]
Since 3.7.3 authorization library nuget was released, I updated Blending app (And Blending.Mapper reference) with newest package and It's working again. I didn't update the reference in headsOmni though, since AFAIK @kegor is updating all the apps with those changes and he should bump all of them almost at the same time.

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/Starcounter.Authorization/commit/304232fcefde338c8b532dfb97f1f73a9f84ff76
