### ISSUE TITLE
Unauthorized user should not be redirected to SignIn

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/authorization#80]
Right now, we have only `unauthenticated` user concept in the Auth library. Because of this, there's no difference between a user that is not signed in and the user that has no access to the specific page. In both cases, there's a redirection to SignIn.

We need to extend it, so by default:
* Unauthenticated user is redirected to SignIn
* Unauthorized user sees 404

@kegor could you do some research, how it's done in ASP.NET claim-based authorization? We should follow pretty much the same patterns.

**Comment by kegor** [comment]
I collected few points regarding following repro-case:
1. Try to open `/UserAdmin`, you will be redirected on the `/SignIn/signin` page, because `UserAdmin.ListUsersPage` has `[Authorize(Policies.CanManageUsers)]` attribute.
2. In the login form you fill creds for the user that doesn't have claims for access to the `UserAdmin.ListUsersPage`.
3. After click on `Sign in` button you'll get infinite redirect.

Points that might be useful in the discussion:
1. First significant point is `ReattachOrCreate` in which we further also calling `_authenticationTicketService.GetCurrentAuthenticationTicket()` 
this method tryes to find `AuthenticationTicket` in the `SystemUserSession` table (in the case of `SignIn` app) by `SessionId` if it will not be found then 
we will try to use token from cookie for association with session (actually creation the row in the `TicketToSession` table).
2. Second stop `SecurityMiddleware.Run` it will check `_pageSecurity.CheckClass(routingInfo.SelectedPageType, routingInfo.Context).Result` and will 
return `_unauthenticatedResponseFactory(routingInfo.Request.Uri)` if it false.
3. Internally `_pageSecurity.CheckClass` will gather all requirements for the access to the page, for example if page has attribute `[Authorize(Policies.CanManageUsers)]`
it will gather requirement `RequireUserName("admin")`.
4. Further if our user do not fill this requirement we return `_unauthenticatedResponseFactory(routingInfo.Request.Uri)` from the `SecurityMiddleware` and this 
factory actually returns responce with `RedirectUrl`.
5. Finally we have `HandleContext` method on the `SignIn.SignInFormViewModel` method, it will perform redirect if the user is signed in (it is true if current user is not null)
and if we have not null redirect url.

**Comment by mmnosek** [comment]
Please check this out: https://github.com/Starcounter/RebelsLounge/issues/35#issuecomment-452775395

**Comment by kegor** [comment]
I sent initial related changes which we were discussed with @mmnosek in this commit (in the separate branch) https://github.com/Starcounter/Starcounter.Authorization/commit/aae09a175f8ba1aedfa2c652961b0cb3adc815ac.

From one side they works as expected:
_For the authorized user_
![successful_signin_with_redirect](https://user-images.githubusercontent.com/17431807/51022080-53654680-1594-11e9-8de0-9b1d51a2074a.gif)
_For the unauthorized user_
![404_response_for_unathorized](https://user-images.githubusercontent.com/17431807/51022109-6841da00-1594-11e9-8293-1bfdbed1f994.gif)

But from other side I would like to clarify and improve few places which are commented for now.

**Comment by kegor** [comment]
Closing this issue because related PR was merged.
